/**
 * This java file consists a class which handles event 
 * generated by the object of GuiIssueReport
 * @author Pulkit Saxena
 * @version 1.0
 * Date 5-Aug-2007
 */
package issueLog;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.awt.datatransfer.*;
import java.io.*;
import java.util.*;

/**
 * This class handles the event .It implements ActionListener
 * interface.
 * @author Pulkit Saxena
 * @version 1.0
 * Date 5-Aug-207
 *
 */
public class GuiIssueReportEvntHandler implements ActionListener{

	GuiIssueReport objGuiIssueReport;
	
	public GuiIssueReportEvntHandler(GuiIssueReport objGuiIssueReport){
	this.objGuiIssueReport = objGuiIssueReport;	
		
		
	}

	/*
     * This method handles the event generated by the
     * object 
     * @return void
     * @param ae -ActionEvent ae
     */

	 public void actionPerformed(ActionEvent ae){
		
    //to recognise who created event
		 String arg=(String)ae.getActionCommand();	 
		 
		 if(arg.equals("Cut"))
	   	 {		 
	   		//writing data to clipboard
	   		 Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
	   	    String text = objGuiIssueReport.textArea.getSelectedText();
	   	    String s = objGuiIssueReport.textArea.getText().replace(text,"");
	   	    objGuiIssueReport.textArea.setText(s);  
	   	    if(text==null) text =objGuiIssueReport.textArea.getText();
	   	    StringSelection selection = new StringSelection(text);
	   	    clipboard.setContents(selection,null);
	   	   }    		 
	   	 
	   	 //event handled for menu item Copy
	   	 else if(arg.equals("Copy"))
	   	 {

	         Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
	         String text = objGuiIssueReport.textArea.getSelectedText();
	         if(text==null) text =objGuiIssueReport.textArea.getText();
	         StringSelection selection = new StringSelection(text);
	        clipboard.setContents(selection,null);
	       
	   	 }
	   
		 //evemt handled for menu tem Paste
	   	 else if(arg.equals("Paste"))
	   	 {
	   		//reading clipboard
	   		 Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
	        DataFlavor flavor = DataFlavor.stringFlavor;
	        if(clipboard.isDataFlavorAvailable(flavor))
	         {
	            try
	              {
	                //writing from clipboard to textarea
	            	String text =(String)clipboard.getData(flavor);               
	               objGuiIssueReport.textArea.append(text);
	               
	              }catch(UnsupportedFlavorException e)
	                {
	            	  //handling exceptions
	             JOptionPane.showMessageDialog ( objGuiIssueReport,new 
	                     String("Can not paste "+e));
	             
	               }
	             catch(IOException e)
	                {
	            	 //handling exceptions
	            	 JOptionPane.showMessageDialog ( objGuiIssueReport,new 
	            	 String("Can not paste "+e));	 
	                }
	             }
	          }   	 
	 
	 }
	
}
